name: Deploy to S3

on:
  push:
    branches:
      - main

env:
  AWS_STATIC_BUCKET_NAME: rocketseat-upload-widget-web-static
  AWS_CDN_BUCKET_NAME: rocketseat-upload-widget-web-cdn
  SOURCE_DIST: ./dist

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        id: checkout
        uses: actions/checkout@v4

      - name: Configure node
        id: configure-node
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Install pnpm
        id: install-pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 9

      - name: Install dependencies
        id: install-dependencies
        run: |
          pnpm install --frozen-lockfile

      - name: Build app
        id: build-app
        run: |
          pnpm run build

      - name: Configure AWS credentials
        id: configure-aws-credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ vars.AWS_REGION }}

      - name: Sync files to static S3
        id: sync-files-to-static-s3
        run: |
          aws s3 sync ${{ env.SOURCE_DIST }} \
            s3://${{ env.AWS_STATIC_BUCKET_NAME }} --delete --exclude '.*git*'

      - name: Sync files to CDN S3
        id: sync-files-to-cdn-s3
        run: |
          aws s3 sync ${{ env.SOURCE_DIST }} \
            s3://${{ env.AWS_CDN_BUCKET_NAME }} --delete --exclude '.*git*'

      - name: Invalidate CloudFront cache
        id: invalidate-cloudfront-cache
        run: |
          aws cloudfront create-invalidation 
            --distribution-id ${{ secrets.AWS_CLOUDFRONT_DISTRIBUTION_ID }} \
            --paths '/*'
