CREATE TABLE IF NOT EXISTS `users` (
	`id` BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY,
	`name`VARCHAR(255) NOT NULL,
	`email` VARCHAR(255) NOT NULL,
	`password` VARCHAR(255) NOT NULL
);

CREATE TABLE IF NOT EXISTS `reports` (
	`id` BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY,
	`price` DECIMAL(10,2)
);