openapi: 3.2.0

info:
  title: Example API docs
  version: 1.0.0
  description: API documentation for the Example API

servers:
  - url: http://localhost:3000

paths:
  /users:
    get:
      summary: Get all users
      parameters:
        - name: page
          in: query
          required: false
          schema:
            type: integer
            minimum: 1
            default: 1
        - name: pageSize
          in: query
          required: false
          schema:
            type: integer
            minimum: 1
            default: 10

      responses:
        "200":
          description: A list of users
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    type: array
                    items:
                      $ref: '#/components/schemas/User'
    post:
      summary: Create a new user
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UserCreate'

components:
  schemas: 
    User: 
      type: object
      properties:
        data:
          type: array
          items:
            type: object
            required:
              - id
              - name # Estando no required mas não sendo obrigatório o torna obrigatório no retorno com valor opcional
              - email
            properties:
              id:
                type: string
                format: uuid
                description: The user ID
              name:
                type: [string, "null"]
                maxLength: 100
                description: The user name
              email:
                type: string
                format: email
                description: The user email

    UserCreate:
      type: object
      required:
        - name
        - email
      properties:
        name:
          type: [string, "null"]
          maxLength: 100
          description: The user name
        email:
          type: string
          format: email
          description: The user email
